### PR TITLE
fix(docs): disable MD external file watcher when not running in dev mode

### LINKED ISSUE #2661: Build watches external MD files
In an effort to reduce the size of component demo MD files I extracted each example into an external `.tsx` file and included it in parent MD file.

It worked fine locally to view components, but the build hangs when running `yarn build:docs`

See [this build](https://app.circleci.com/pipelines/github/patternfly/patternfly-react/13156/workflows/2e68a291-ae6b-457b-8a87-41a2e5970e82/jobs/64246) for context

### PR DESCRIPTION
**Pull request by mturley**
Fixes #2661

### CODE REVIEW

File: packages/theme-patternfly-org/scripts/md/parseMD.js [hunk 1]
```diff
@@ -277,9 +279,11 @@ module.exports = {
...
     sync(glob, { ignore }).forEach(sourcePropsFile);
   },
-  sourceMD(glob, source, ignore) {
-    globs.md.push({ glob, source, ignore });
-    sync(glob, { ignore }).forEach(file => sourceMDFile(file, source));
+  sourceMD(buildMode) {
+    return function(glob, source, ignore) {
+      globs.md.push({ glob, source, ignore });
+      sync(glob, { ignore }).forEach(file => sourceMDFile(file, source, buildMode));
+    }
```
Comment (redallen) [inline packages/theme-patternfly-org/scripts/md/parseMD.js:286]: Can you move this to `generate.js` instead? Something like:
```js
const sourceMDWithOptions = (...args) => sourceMD(...args, options._name);
```

**Review by redallen — CHANGES_REQUESTED** [review]

File: packages/theme-patternfly-org/scripts/md/parseMD.js (hunk 1 above)
Comment (mturley) [reply packages/theme-patternfly-org/scripts/md/parseMD.js:286]: Sure. I went back and forth on doing this a few different ways, wasn't super happy with it anyway.

**Review by redallen — APPROVED** [review]
Thanks @mturley !!
