### PR TITLE
fix(docs): removed Blog masthead/footer links, pointed Get in touch page to Medium

### LINKED ISSUE #1572: Remove blog from site
1. Pull the blog from the site completely. Including link on masthead.
2. Then on the Get in touch page we would change the copy to Medium rather than blog and link to the PatternFly medium page. Copy should say "PatternFly Medium"
Screen Shot 2019-12-04 at 2 02 33 PM
3. Remove the "B" for blog icon and replace it with the Catalog icon:
Screen Shot 2019-12-04 at 2 09 48 PM

### PR DESCRIPTION
**Pull request by evwilkin**
fixes #1572

### CODE REVIEW

File: packages/patternfly-4/gatsby-theme-patternfly-org/layouts/sideNavLayout.js [hunk 1]
```diff
@@ -231,7 +231,7 @@ const SideNavLayout = ({
   // Wrap in a div to force scrolling the same content
   // TODO: SEO
   return (
-    <div className="ws-site-root">
+    <div>
```
Comment (redallen) [inline packages/patternfly-4/gatsby-theme-patternfly-org/layouts/sideNavLayout.js]: This needs to be removed in all other layouts as well.
