### PR TITLE
fix(docs): fix axe issues on home page

### LINKED ISSUE #3622: Bug - UI issues / axe violations raised by sideNavLayout
**Describe the problem**
A clear and concise description of the problem. Which pages are affected?
These axe violations of sideNavLayout were discovered upon review of #3573 - sideNavLayout may need structural updates to resolve these violations following conversation with @jessiehuff 

Screenshot 2023-06-22 at 4 44 05 PM

As noted by @thatblindgeye : 

> The toolbar items that include the theme toggle => release selector get kinda bunched up at smaller viewports (main issue is probably the release toggle getting cut off so much)
image

### PR DESCRIPTION
**Pull request by evwilkin**
Closes #3622 

This PR:
- Fixes "all page content should be contained by landmarks" a11y issue with GDPR banner on the homepage.
- No need to fix 1 remaining landmarks a11y issue, as it relates to the "Skip to content" link and the [a11y docs](https://dequeuniversity.com/rules/axe/4.7/region?application=AxeChrome) state:

> It is best practice to contain all content **excepting skip links**, within distinct regions such as the header, nav, main, and footer.

- Fixes a11y issues not noted in original issue of missing labels for Cards on homepage.
- Unrelated to a11y, this PR also reduces code repetition by pulling out the hard coded blog post cards into a new `<FeaturedBlogCard />` component (similar to the existing `<AggregateCards />` component) and mapping through the blog post array.

### CODE REVIEW

File: packages/documentation-framework/components/gdprBanner/gdprBanner.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ export const GdprBanner = () => {
   }
 
   return !isBannerOpen ? null : (
-    <div className="ws-gdpr-banner-container pf-v5-l-flex">
+    <section aria-labelledby="ws-gdpr-banner-text" className="ws-gdpr-banner-container pf-v5-l-flex">
```
Comment (thatblindgeye) [inline packages/documentation-framework/components/gdprBanner/gdprBanner.js:16]: Nit: this can cause a rather verbose output for the section's accessible name when traversing the rotor menu for something like VO or JAWS. Wondering if instead of `aria-labelledby` if `aria-label` would be better for a more succinct label. "Cookies on PatternFly" or something. Probably not a blocker, though, since it does provide the info to the user with less potential to "miss it" (outside of literally skipping past it before a user's AT can announce it fully)

File: packages/documentation-site/patternfly-docs/pages/home.js [hunk 2]
```diff
@@ -112,6 +117,40 @@ const AggregateCards = () => {
...
+  const actionId = `card-article-input-${idx}`;
+
+  return (
+    <Card id={cardId} component="div" isClickable key={idx} aria-labelledby={`featured-blog-post-${idx}-title`}>
+      <CardHeader
+        className="v5-featured-posts-card-header-img"
+        selectableActions={{
+          to: URL,
+          selectableActionId: actionId,
+          selectableActionAriaLabelledby: cardId,
```
Comment (thatblindgeye) [inline packages/documentation-site/patternfly-docs/pages/home.js:132]: This should probably be set to the `featured-blog-post-${idx}-title` text instead (assuming there will always be a title). Right now, at least in VO, these cards just come up as "radio button X of Y" in the VO rotor menu; updating one of them to the `featured-blog-post-0-title` causes it to render with a more meaningful description.

The same would probably apply to the AggregateCards as well

File: packages/documentation-framework/components/gdprBanner/gdprBanner.js (hunk 1 above)
Comment (evwilkin) [reply packages/documentation-framework/components/gdprBanner/gdprBanner.js:16]: Thanks for the clarification, that makes sense - I will adopt your suggestion

File: packages/documentation-site/patternfly-docs/pages/home.js (hunk 2 above)
Comment (evwilkin) [reply packages/documentation-site/patternfly-docs/pages/home.js]: Thanks, this makes sense - made this update here and in AggregateCards as well

**Review by thatblindgeye — APPROVED** [review]
🎉

File: packages/documentation-site/patternfly-docs/pages/home.js [hunk 3]
```diff
@@ -216,102 +259,9 @@ const HomePage = () => (
...
-            <a href={featuredPostsData.post4.URL}>
-              {featuredPostsData.post4.title}
-            </a>
-          </CardTitle>
-          <CardFooter className="pf-v5-u-color-200">
-            {featuredPostsData.post4.author} • {featuredPostsData.post4.length}
-          </CardFooter>
-        </Card>
+        {Object.values(featuredPostsData).map((post, idx) => (
+          <FeaturedBlogCard postData={post} idx={idx} key={`${idx}-${post.title}`} />
```
Comment (jenny-s51) [inline packages/documentation-site/patternfly-docs/pages/home.js:263]: Good thinking to keep this DRY 👍

File: packages/documentation-framework/components/gdprBanner/gdprBanner.js [hunk 4]
```diff
@@ -13,7 +13,7 @@ export const GdprBanner = () => {
   }
 
   return !isBannerOpen ? null : (
-    <div className="ws-gdpr-banner-container pf-v5-l-flex">
+    <section aria-label="Cookies on PatternFly" className="ws-gdpr-banner-container pf-v5-l-flex">
```
Comment (jenny-s51) [inline packages/documentation-framework/components/gdprBanner/gdprBanner.js:16]: Sounds great in VO now
