### PR TITLE
(fix): id attribute value must be unique for a11y issues

### LINKED ISSUE #1313: Fix a11y issues in Documentation/React/Empty-state
https://www.patternfly.org/v4/documentation/react/components/emptystate/

There is 1 type of a11y issues (the rest are covered by other issues)

1. id attribute value must be unique

Screen Shot 2019-07-17 at 10 09 26 AM

Steps to reproduce the a11y errors:
1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1324: Fix a11y issues in Documentation/Core/Alert-group
https://www.patternfly.org/v4/documentation/core/components/alertgroup

There is 1 type of a11y issue(the rest are covered by separate issues):
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1327: Fix a11y issues in Documentation/Core/Card
https://www.patternfly.org/v4/documentation/core/components/card

There is 1 type of a11y issue in this page(the rest are covered by separate issues:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1328: Fix a11y issues in Documentation/Core/Chip
https://www.patternfly.org/v4/documentation/core/components/chip

There is 1 type of a11y issue(rest are in separate issues):
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1334: Fix a11y issues in Documentation/Components/NotificationBadge
https://www.patternfly.org/v4/documentation/core/components/notificationbadge

There is 1 type of a11y issue:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1338: Fix a11y issues in Documentation/Core/Skiptocontent
https://www.patternfly.org/v4/documentation/core/components/skiptocontent

There is 1 type of a11y issue:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1339: Fix a11y issues in Documentation/Core/Switch
https://www.patternfly.org/v4/documentation/core/components/switch

There is 1 type of a11y issue:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1340: Fix a11y issues in Documentation/Core/TabContent
https://www.patternfly.org/v4/documentation/core/components/tabcontent

There is 1 type of a11y issue:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1342: Fix a11y issues in Documentation/Core/Wizard
https://www.patternfly.org/v4/documentation/core/components/wizard

There is 1 a11y issue:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1344: Fix a11y issues in Level
https://www.patternfly.org/v4/documentation/core/layouts/level

There is 1 a11y issue:
id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1347: Fix a11y issues in Documentation/Core/Demos/cardview
https://www.patternfly.org/v4/documentation/core/demos/cardview

There is 1 type of a11y issue:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### LINKED ISSUE #1349: Fix a11y issues in Documentation/Core/Demos/Modal
https://www.patternfly.org/v4/documentation/core/demos/modal

There is 1 a11y issue:
1. id attribute value must be unique

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

### PR DESCRIPTION
**Pull request by jessiehuff**
Fixes #1349
Fixes #1347
Fixes #1344
Fixes #1342
Fixes #1340
Fixes #1339
Fixes #1338
Fixes #1334
Fixes #1328
Fixes #1327
Fixes #1324
Fixes #1313

### CODE REVIEW

File: packages/patternfly-4/src/components/_core/Documentation/index.js [hunk 1]
```diff
@@ -57,7 +57,7 @@ export default class Documentation extends React.Component {
                 <SEO title="HTML" />
                 <PageSection variant={PageSectionVariants.light} className="pf-site-background-medium">
                   <AutoLinkHeader size="md" is="h1" className="pf4-site-framework-title">HTML</AutoLinkHeader>
-                  <AutoLinkHeader size="4xl" is="h2" className="pf-u-mt-sm pf-u-mb-md">{heading}</AutoLinkHeader>
+                  <AutoLinkHeader size="4xl" is="h2" id={`${heading.replace(/ /g, '-')}-title`} className="pf-u-mt-sm pf-u-mb-md">{heading}</AutoLinkHeader>
```
Comment (jschuler) [inline packages/patternfly-4/src/components/_core/Documentation/index.js]: The AutoLinkHeader generates the ids from the text, so this would break that

File: packages/patternfly-4/src/templates/mdxPF4Template.js [hunk 2]
```diff
@@ -46,7 +46,7 @@ const MdxPF4Template = ({ data }) => {
       <SEO title="React" />
       <PageSection variant={PageSectionVariants.light} className="section-border pf-site-background-medium">
         <AutoLinkHeader size="md" is="h1" className="pf4-site-framework-title">React</AutoLinkHeader>
-        <AutoLinkHeader size="4xl" is="h2" className="pf-u-mt-sm pf-u-mb-md">
+        <AutoLinkHeader size="4xl" is="h2" id={`${data.mdx.frontmatter.title.replace(/ /g, '-')}-title`} className="pf-u-mt-sm pf-u-mb-md">
```
Comment (jschuler) [inline packages/patternfly-4/src/templates/mdxPF4Template.js]: Same comment here, id would overwrite the generated one. perhaps we can add a new suffix prop and pass title into it?

File: packages/patternfly-4/src/components/_core/Documentation/index.js (hunk 1 above)
Comment (jessiehuff) [reply packages/patternfly-4/src/components/_core/Documentation/index.js]: That's a really good point, thanks! I updated it, let me know what you think. :)

File: packages/patternfly-4/plugins/gatsby-transformer-react-docgen-typescript/gatsby-node.js [hunk 3]
```diff
@@ -1,11 +1,13 @@
...
+  console.log('node', node.relativePath)
   if (
     !node ||
-    node.relativePath.indexOf('/example') !== -1 ||
-    node.relativePath.indexOf('.docs') !== -1 ||
-    node.relativePath.indexOf('.md') !== -1
+    node.relativePath.indexOf('/example') >= 0 ||
+    node.relativePath.indexOf('.docs') >= 0 ||
+    node.relativePath.indexOf('.md') >= 0 ||
+    node.relativePath.indexOf('patternfly-3') >= 0
```
Comment (jschuler) [inline packages/patternfly-4/plugins/gatsby-transformer-react-docgen-typescript/gatsby-node.js]: I like the suffix addition, thanks! Curious about the changes in example-styles.css and this gatsby-node.js though, are they related?

Comment (jessiehuff) [reply packages/patternfly-4/plugins/gatsby-transformer-react-docgen-typescript/gatsby-node.js]: Gatsby was pulling in Patternfly 3 in the markdown for some reason so it was showing both as having the same id and failing axe. I asked Zack to take a look at it, and he actually added that fix and told me it was due to the way he originally wrote it. I believe it just tells the markdown to ignore Patternfly 3 here. I am noticing that I accidentally included the console.log though so I'll take that out!

**Comment by jschuler** [comment]
Thanks @jessiehuff
