### PR TITLE
fix(404): use v4 404 page

### LINKED ISSUE #975: 404 message brings you to a page which navigates to the old PF site when clicking on the PF logo
When getting a 404, you are brought to this page:
Screen Shot 2019-04-26 at 5 39 18 PM
When clicking the logo on the masthead, you are brought to the old PF site
Screen Shot 2019-04-26 at 5 39 27 PM

### PR DESCRIPTION
**Pull request by redallen**
Fixes #975

### CODE REVIEW

File: scripts/combine-sites.js [hunk 1]
```diff
@@ -10,53 +10,30 @@ const build_root = 'out/';
...
-        // eslint-disable-next-line no-console
-        return console.error(errPf3);
-      }
-      // eslint-disable-next-line no-console
-      console.log(`Copied pf3 build into ${build_root}`);
-    });
-  });
-});
\ No newline at end of file
+fs.removeSync(build_root);
```
Comment (dgutride) [inline scripts/combine-sites.js]: super risky to do anything today that changes the way we build the site - recommend we wait until Monday or until we can stage first

Comment (redallen) [reply scripts/combine-sites.js]: This was here before `fs.remove(build_root, (errRemove) =>`. Just remove last build dir in case it exists.
