### PR TITLE
fix(sideNavLayout):replace use of PageHeader with Masthead

### LINKED ISSUE #3053: Use masthead instead of page header
Can we update this to use the masthead?

https://github.com/patternfly/patternfly-org/blob/9380bcb7a683ec4758f5ac144f214f26a63c0d0f/packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js#L211-L225

### PR DESCRIPTION
**Pull request by nicolethoen**
Closes #3053

### CODE REVIEW

**Comment by evwilkin** [comment]
@nicolethoen pushed my updates to implement the expandable SearchInput with algolia, and was also able to rip out several stale CSS rules 👍

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js [hunk 1]
```diff
@@ -45,111 +55,106 @@ const HeaderTools = ({
...
+    <Toolbar isFullHeight>
+      <ToolbarContent>
+        {topNavItems.length > 0 && (
+          <ToolbarItem className="pf-m-overflow-container">
+            <TopNav navItems={topNavItems} />
+          </ToolbarItem>
+        )}
+        <ToolbarGroup
+          alignment={{ default: 'alignRight' }}
+          spacer={{ default: 'spacerNone', md: 'spacerMd' }}
```
Comment (mattnolting) [inline packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js:84]:
```suggestion
          spacerItems={{ default: 'spacerNone', md: 'spacerMd' }}
```

**Review by mattnolting — CHANGES_REQUESTED** [review]
Looking good! Saw a few things we can clean up..

Looks to me like this dropdown text shouldn't wrap a mobile views, rather it should truncate. 

Current:
Screen Shot 2022-11-01 at 10 19 41 AM

Updated:
Screen Shot 2022-11-01 at 10 25 33 AM

And it looks like we need to add `min-width: 0` to `.pf-c-toolbar__item`, so replace https://github.com/patternfly/patternfly-org/pull/3224/files#diff-3512b9f9de6b73548461009275d974f097637d70bde1c1b724d30d5a45e8b146R64-R66

```
.ws-masthead .pf-c-toolbar  {
  min-width: 0;
}
```

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css [hunk 2]
```diff
@@ -95,10 +61,9 @@
   border-bottom: 2px solid #fff;
 }
 /* For tiny (200px) viewports */
-.ws-org-version-switcher .pf-c-dropdown__toggle  >.pf-c-dropdown__toggle-text {
-  white-space: normal;
+.ws-masthead .pf-c-toolbar  {
```
Comment (mattnolting) [inline packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css:64]: Sorry, need to target `.ws-masthead .pf-c-toolbar__item` here

**Review by mattnolting — DISMISSED** [review]
Love it! LPTM 🎉

**Review by evwilkin — DISMISSED** [review]
LGTM

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js [hunk 3]
```diff
@@ -45,111 +55,105 @@ const HeaderTools = ({
...
+              target="top"
+              aria-label="Link to PatternFly GitHub page"
+              className="ws-github-pageheader"
+            >
+              <GithubIcon />
+            </Button>
+          </ToolbarItem>
+          {hasVersionSwitcher && (
+            <ToolbarItem>
+              <Dropdown
```
Comment (mcoker) [inline packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js:118]: I believe this should be the full height variation, that's what we're doing with dropdowns in the masthead like this AFAIK. Also there are custom styles on this making it shift around on hover and when it's expanded - IMO it would be much better as a plain ol' dropdown without the custom stuff. 

Nov-17-2022 18-59-29

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js [hunk 4]
```diff
@@ -209,20 +210,31 @@ export const SideNavLayout = ({ children, groupedRoutes, navOpen: navOpenProp })
...
-  );
+    <Masthead className="ws-masthead">
+      <MastheadToggle>
+        <PageToggleButton variant="plain" aria-label="Global navigation">
+          <BarsIcon />
+        </PageToggleButton>
+      </MastheadToggle>
+      <MastheadMain>
+        <MastheadBrand href={prurl || pathPrefix || '/'}>
+          {prnum ? `PR #${prnum}` : <Brand src={logo} alt="Patternfly Logo" />}
```
Comment (mcoker) [inline packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js:221]: It may be worth considering using the logo from core, it's bigger and looks better IMO - https://github.com/patternfly/patternfly/blob/5eee883c9aadfa4834798de2ee3c00dfa8a37a6a/src/patternfly/demos/Masthead/masthead-template.hbs#L15-L20

**Review by mcoker — APPROVED** [review]
LGTM. Left some comments, but they're pre-existing, so they don't need to block this PR if we want to merge it.

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js (hunk 4 above)
Comment (nicolethoen) [reply packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js:221]: Do you know offhand the best way to do that? Is it already something I can import and use or should I copy and paste an svg from core here?

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js (hunk 3 above)
Comment (mcoker) [reply packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js:117]: @mcarrano @mceledonia wdyt? ^

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js (hunk 4 above)
Comment (mcoker) [reply packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js:219]: On org anyways, the core demo images are at `/assets/images/...`. So they're already there somewhere :D 

I'm not sure if there is a best practice around `import`ing the file and referencing it like most of the react examples do, but you could just do it like this which is pretty simple

```
var logoMd = '/assets/images/logo__pf--reverse-on-md.svg';
var logo = '/assets/images/logo__pf--reverse--base.svg';
var logoBase = '/assets/images/logo__pf--reverse--base.png';

<Brand src={logoBase} alt="PatternFly logo" widths={{ default: '180px', md: '220px' }}>
  <source media="(min-width: 768px)" srcSet={logoMd} />
  <source srcSet={logo} />
 </Brand>
```

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js [hunk 5]
```diff
@@ -209,20 +210,36 @@ export const SideNavLayout = ({ children, groupedRoutes, navOpen: navOpenProp })
...
+    <Masthead className="ws-masthead">
+      <MastheadToggle>
+        <PageToggleButton variant="plain" aria-label="Global navigation">
+          <BarsIcon />
+        </PageToggleButton>
+      </MastheadToggle>
+      <MastheadMain>
+        <MastheadBrand href={prurl || pathPrefix || '/'}>
+          {prnum ? `PR #${prnum}` : (
+            <Brand src={logoBase} alt="PatternFly logo" widths={{ default: '180px', md: '220px' }}>
```
Comment (mcoker) [inline packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js:222]: oops! I gave you the wrong breakpoint. This will match core.

```suggestion
            <Brand src={logoBase} alt="PatternFly logo" widths={{ default: '180px', '2xl': '220px' }}>
```

**Review by mcoker — CHANGES_REQUESTED** [review]
Just one little nit about the brand image width.

File: packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css [hunk 6]
```diff
@@ -27,78 +27,24 @@
...
-    display: none;
-    visibility: hidden;
-  }
-}
 @media (max-width: 430px) {
   .ws-page-header > .pf-c-page__header-brand > .pf-c-page__header-brand-link {
     display: none;
     visibility: hidden;
   }
 }
```
Comment (mcoker) [inline packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css]: Just noticed this - do we need it still?

**Review by mcoker — APPROVED** [review]
🚀

**Comment by nicolethoen** [comment]
I think this is ready to merge, @evwilkin ?

**Review by evwilkin — APPROVED** [review]
LGTM
