### PR TITLE
fix(docs): hardcode Tile deprecation, fix console errors

### LINKED ISSUE #4176: Bug - docs framework console warning building core
Running `yarn build` on core gives this console warning

```
[...]
prender /
prender /404
prender /components/about-modal
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <List>. See https://reactjs.org/link/warning-keys for more information.
    at ListItem (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:2230:11)
    at CSSVariables (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:67072:5)
    at div
    at StackItem (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:102602:11)
    at div
    at Stack (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:102576:11)
    at div
    at MDXChildTemplate.components.about-modal.html
    at div
    at RouterImpl (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:223:5)
    at Location (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:52:23)
    at Router
    at div
    at PageBody (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:95643:11)
    at section
    at PageSection (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:95805:11)
    at div
    at PageGroup (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:95741:11)
    at MDXTemplate (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:122135:3)
    at AppRoute (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:122328:3)
    at main
    at FocusHandlerImpl (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:347:5)
    at FocusHandler (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:318:19)
    at RouterImpl (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:223:5)
    at Location (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:52:23)
    at Router
    at div
    at div
    at div
    at Page (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:95475:9)
    at SideNavLayout (/Users/cmichael/repos/patternfly/.cache/ssr-build/main.js:86794:3)
    at SideNavRouter
    at div
    at FocusHandlerImpl (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:347:5)
    at FocusHandler (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:318:19)
    at RouterImpl (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:223:5)
    at Location (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:52:23)
    at Router
    at App
    at ServerLocation (/Users/cmichael/repos/patternfly/node_modules/@reach/router/index.js:160:19)
prender /components/about-modal/html-demos
prender /components/accordion
prender /components/action-list
prender /components/alert
prender /components/alert/html-demos
[...]
```

### LINKED ISSUE #4339: Bug - Mark tile as deprecated
**Describe the problem**
Mark the tile as deprecated.

### LINKED ISSUE #4340: Bug - Console error for footer class
Docs-framework throws a console error for use of `class` in the footer that needs to be updated to `className`.

Image

### PR DESCRIPTION
**Pull request by evwilkin**
Closes #4339 
Closes #4176 
Closes #4340 

FYI - Line changes linked due to additional prettier formatting changes.

This PR:
- Fixes console errors:
  - error thrown by missing `key` prop in CSSVariables table. (cssVariables.js [line 15](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-364df80da54886753ca572b74c68a1a32893da16c7a4d9c76d762725ff51f228R15))
  - error thrown by use of `class` rather than `className` in the site footer. (footer.js [line 270](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-4ffaf2430cb77de5fb6652969a79ce1202dca821889f6ae5358c8adc6ca33dc9R270))

- Hard-codes "Tile" to be deprecated:
  - Adds "deprecated" label to the Sidenav item (sideNav.js [line 169](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-8e3c7674b90a7a160ac769d32b003a8c5ba29ee93599606701fd47312630fc0aR169))
    - _Explanation: sidenav label isn't added if either the React or Core examples aren't marked deprecated, this line bypasses that check specifically for the `Tile` component._
  - Adds inline alert to the top of each Tile docs page (mdx.js [line 125](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-da135efaa2b01f501f1ac196874e6c6ae745345196f59a4581445639bf5384c4R125))
    - _Explanation: Inline deprecation alert is only added on Core page if examples exist in a `/deprecated/` directory, this bypasses that specifically for the `Tile` component._
  - Adds TODO comments to remove these hard-coded updates when [Core #7178](https://github.com/patternfly/patternfly/pull/7178) is merged. ([sideNav.js](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-8e3c7674b90a7a160ac769d32b003a8c5ba29ee93599606701fd47312630fc0aR167-R168) && mdx.js)

### CODE REVIEW

File: packages/documentation-framework/templates/mdx.js [hunk 1]
```diff
@@ -25,60 +41,107 @@ const MDXChildTemplate = ({
...
+            Beta components
+          </a>{' '}
+          page on GitHub.
         </InlineAlert>
       )}
-      {(deprecated || source === 'react-deprecated' || source === 'html-deprecated') && (
+      {(deprecated ||
+        source === 'react-deprecated' ||
+        source === 'html-deprecated' ||
+        // TODO: remove hardcoded Tile when Core PR merges
```
Comment (tlabaj) [inline packages/documentation-framework/templates/mdx.js:123]: Can we open a follow up issues so we don't forget to do this?

Comment (evwilkin) [reply packages/documentation-framework/templates/mdx.js:123]: Thank you!  Created here - https://github.com/patternfly/patternfly-org/issues/4343

**Review by dlabaj — APPROVED** [review]

**Review by tlabaj — APPROVED** [review]
