### PR TITLE
fix(docs): fixed broken links & allowed mixed case links

### LINKED ISSUE #1501: Wrong link to PatternFly template in "Get started" page
The link to the **PatternFly template** under the [Download the template file](https://www.patternfly.org/v4/get-started/designers#download-the-template-file) paragraph in [https://www.patternfly.org/v4/get-started/designers](https://www.patternfly.org/v4/get-started/designers) links to the wrong file: [https://sketch.cloud/s/r9k28](https://sketch.cloud/s/r9k28)

### PR DESCRIPTION
**Pull request by evwilkin**
fixes #1501

### CODE REVIEW

File: packages/patternfly-4/src/templates/contentTemplate.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ import CoreSideNav from '../components/_core/Documentation/SideNav';
 import './template.scss';
 
 const components = {
```
Comment (redallen) [inline packages/patternfly-4/src/templates/contentTemplate.js]: Could have just removed this, but this is all being scrapped soon anyway!

File: packages/patternfly-4/src/templates/contentTemplate.js [hunk 2]
```diff
@@ -20,7 +20,7 @@ import CoreSideNav from '../components/_core/Documentation/SideNav';
...
-  a: props => <a {...props} href={props.href ? props.href.toLowerCase() : props.href} />
+  a: props => <a {...props} href={props.href} />
```
Comment (jschuler) [inline packages/patternfly-4/src/templates/contentTemplate.js]: you could remove this component now since we're not doing anything special to it
